# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/consumption.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/consumption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/consumption.proto\x12\x0b\x63onsumption\"B\n\x12\x43onsumptionRequest\x12\x16\n\x0estart_datetime\x18\x01 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x02 \x01(\t\";\n\x11\x43onsumptionRecord\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x14\n\x0c\x65nergy_usage\x18\x02 \x01(\x01\"F\n\x13\x43onsumptionResponse\x12/\n\x07records\x18\x01 \x03(\x0b\x32\x1e.consumption.ConsumptionRecord2m\n\x12\x43onsumptionService\x12W\n\x12GetConsumptionData\x12\x1f.consumption.ConsumptionRequest\x1a .consumption.ConsumptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.consumption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSUMPTIONREQUEST']._serialized_start=40
  _globals['_CONSUMPTIONREQUEST']._serialized_end=106
  _globals['_CONSUMPTIONRECORD']._serialized_start=108
  _globals['_CONSUMPTIONRECORD']._serialized_end=167
  _globals['_CONSUMPTIONRESPONSE']._serialized_start=169
  _globals['_CONSUMPTIONRESPONSE']._serialized_end=239
  _globals['_CONSUMPTIONSERVICE']._serialized_start=241
  _globals['_CONSUMPTIONSERVICE']._serialized_end=350
# @@protoc_insertion_point(module_scope)
